git:
  url: /repository
ingress:
  domainName: example.kuberpult.com
cd:
  resources:
    requests:
      cpu: 500m
      memory: 1Gi
    limits:
      cpu: 500m
      memory: 1Gi
frontend:
  resources:
    requests:
      cpu: 250m
    limits:
      cpu: 250m
environment_configs:
  environment_configs_json: |
    {
      "production": {
        "upstream": {
            "latest": true
         },
         "argocd" :{}
      }
    }
 
