# This workflow creates a new release in github, when a tag is pushed.
name: "Release kuberpult"
'on':
  push:
    tags:
      - "*"
jobs:
  execution-plan:
    uses: ./.github/workflows/execution-plan-snippet.yml
    with:
      trigger: tag
    secrets: inherit

  lint-and-test-helm-chart:
    needs: [execution-plan]
    uses: ./.github/workflows/test-helm-chart-release.yml
    with:
      trigger: tag
    secrets: inherit

  release:
    needs: [execution-plan, lint-and-test-helm-chart]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Set version
        id: version
        run: |
          echo "VERSION=${GITHUB_REF#refs/tags/}"  >> $GITHUB_ENV
          echo "version=${GITHUB_REF#refs/tags/}" >> $GITHUB_OUTPUT
      - name: Create helm chart for release
        run: |
          make -C charts/kuberpult release-tag
      - name: Release
        uses: ./.github/actions/softprops-action-gh-release
        with:
          files: |
            charts/kuberpult/kuberpult-${{ steps.version.outputs.version }}.tgz
          body: |
            Release ${{ steps.version.outputs.version }}
          tag_name: ${{ steps.version.outputs.version }}
          generate_release_notes: true
          draft: true
