name: "Release kuberpult"
'on':
  push:
    tags:
      - "*"
jobs:
  generate_version:
    runs-on: ubuntu-latest
    steps:
      - name: Get the version
        id: get_version
        run: |
          echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
    outputs:
      version: ${{ steps.get_version.outputs.VERSION }}

  execution-plan:
    needs: generate_version
    if: false
    uses: ./.github/workflows/execution-plan-snippet.yml
    with:
      trigger: main
      version: ${{ needs.generate_version.outputs.version }}  
    secrets: inherit

  release:
    needs: [generate_version, execution-plan]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Save version
        run: |
          echo ${{ needs.generate_version.outputs.version }} > version
      - name: Create helm chart for release
        run: |
          make -C charts/kuberpult release-tag
      - name: Release
        uses: ./.github/actions/softprops-action-gh-release
        with:
          files: |
            charts/kuberpult/kuberpult-${{ needs.generate_version.outputs.version }}.tgz
          body: |
            Release ${{ needs.generate_version.outputs.version }}
          tag_name: ${{ needs.generate_version.outputs.version }}
          generate_release_notes: true
          draft: true
          
